### ISSUE TITLE
Compiling Issues with tradle engine

### ISSUE THREAD

**Issue by corgidesu** [tradle/engine#1]
Hi,

I'm trying to compile the tradle engine and run the application but I encounter the following issue:

> In file included from ../src/WebWorkerThreads.cc:12:0:
>../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanError(const char*)’:
>../node_modules/nan/nan.h:319:38: error: ‘New’ is not a member of ‘v8::String’
> \# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
>                                      ^
>../node_modules/nan/nan.h:339:13: note: in expansion of macro ‘_NAN_ERROR’
>     return  _NAN_ERROR(v8::Exception::Error, errmsg);
>             ^
>../node_modules/nan/nan.h: In function ‘void NanThrowError(const char*)’:
>../node_modules/nan/nan.h:324:7: error: ‘ThrowException’ is not a member of ‘v8’
>       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \

Looking at the Travis CI build of your project:
https://travis-ci.org/tradle/engine

The logs in npm install in the travis CI also show the same errors. 

When trying to run index.js from engine, I get the following errors:

> const {
>      ^
>SyntaxError: Unexpected token {
>    at exports.runInThisContext (vm.js:53:16)
>    at Module._compile (module.js:374:25)
>    at Object.Module._extensions..js (module.js:417:10)

Is the above npm install command causing this problem to occur?

Thanks in Advance,
Victa

**Comment by mvayngrib** [comment]
@corgidesu you probably have an older version of node, try node version 6
